<a href="https://colab.research.google.com/github/MuntasirAraf14/Funnel_Data_Analysis/blob/main/Funnel_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Set-up

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

#Corporate Styling

In [2]:
plt.style.use('seaborn-v0_8')
sns.set_palette('husl')

print("Everything is fine")

Everything is fine

In [3]:
df = pd.read_csv("funnel_analysis_data.csv")
df

,User_ID,Session_ID,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag
0,USR00001,SES00001,Browse,2025-10-28 07:33:50,Desktop,West,Organic,Home,0.00,Yes
1,USR00001,SES00001,Add to Cart,2025-10-28 07:36:50,Tablet,East,Social Media,Beauty,0.00,Yes
2,USR00001,SES00001,Checkout,2025-10-28 07:40:50,Mobile,West,Email,Beauty,0.00,Yes
3,USR00002,SES00002,Browse,2025-10-19 09:15:10,Desktop,East,Email,Electronics,0.00,No
4,USR00002,SES00002,Add to Cart,2025-10-19 09:18:10,Mobile,West,Social Media,Fashion,0.00,No
...,...,...,...,...,...,...,...,...,...,...
21658,USR09999,SES09999,Browse,2025-10-03 17:22:58,Desktop,South,Google Ads,Electronics,0.00,No
21659,USR09999,SES09999,Add to Cart,2025-10-03 17:26:58,Tablet,West,Social Media,Fashion,0.00,No
21660,USR09999,SES09999,Checkout,2025-10-03 17:29:58,Mobile,North,Email,Fashion,0.00,No
21661,USR09999,SES09999,Purchase,2025-10-03 17:34:58,Mobile,East,Email,Fashion,960.65,No
21662,USR10000,SES10000,Browse,2025-10-15 20:32:43,Mobile,South,Google Ads,Beauty,0.00,Yes

##Perform Basic STEPS

In [5]:
print("Top 5data\n")
display(df.head())

Top 5data

,User_ID,Session_ID,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag
0,USR00001,SES00001,Browse,2025-10-28 07:33:50,Desktop,West,Organic,Home,0.0,Yes
1,USR00001,SES00001,Add to Cart,2025-10-28 07:36:50,Tablet,East,Social Media,Beauty,0.0,Yes
2,USR00001,SES00001,Checkout,2025-10-28 07:40:50,Mobile,West,Email,Beauty,0.0,Yes
3,USR00002,SES00002,Browse,2025-10-19 09:15:10,Desktop,East,Email,Electronics,0.0,No
4,USR00002,SES00002,Add to Cart,2025-10-19 09:18:10,Mobile,West,Social Media,Fashion,0.0,No

In [12]:
df.tail()

,User_ID,Session_ID,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag
21658,USR09999,SES09999,Browse,2025-10-03 17:22:58,Desktop,South,Google Ads,Electronics,0.00,No
21659,USR09999,SES09999,Add to Cart,2025-10-03 17:26:58,Tablet,West,Social Media,Fashion,0.00,No
21660,USR09999,SES09999,Checkout,2025-10-03 17:29:58,Mobile,North,Email,Fashion,0.00,No
21661,USR09999,SES09999,Purchase,2025-10-03 17:34:58,Mobile,East,Email,Fashion,960.65,No
21662,USR10000,SES10000,Browse,2025-10-15 20:32:43,Mobile,South,Google Ads,Beauty,0.00,Yes

In [8]:
#Random Data from Dataset
df.sample()

,User_ID,Session_ID,Event,Timestamp,Device,Region,Channel,Product_Category,Revenue,Bounce_Flag
4729,USR02201,SES02201,Add to Cart,2025-10-12 04:02:40,Tablet,South,Social Media,Beauty,0.0,Yes

In [13]:
print(df.columns)
print(f"\ntotal Number of Columns:-  {df.columns.nunique()}")

Index(['User_ID', 'Session_ID', 'Event', 'Timestamp', 'Device', 'Region',
       'Channel', 'Product_Category', 'Revenue', 'Bounce_Flag'],
      dtype='object')

total Number of Columns:-  10

In [11]:
#type of dataset

type(df)

pandas.core.frame.DataFrame

In [14]:
df.dtypes

User_ID              object
Session_ID           object
Event                object
Timestamp            object
Device               object
Region               object
Channel              object
Product_Category     object
Revenue             float64
Bounce_Flag          object
dtype: object

In [15]:
#timestamp column must be in date time type

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
print(df.dtypes)

User_ID                     object
Session_ID                  object
Event                       object
Timestamp           datetime64[ns]
Device                      object
Region                      object
Channel                     object
Product_Category            object
Revenue                    float64
Bounce_Flag                 object
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21663 entries, 0 to 21662
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           21663 non-null  object
 1   Session_ID        21663 non-null  object
 2   Event             21663 non-null  object
 3   Timestamp         21663 non-null  datetime64[ns]
 4   Device            21663 non-null  object
 5   Region            21663 non-null  object
 6   Channel           21663 non-null  object
 7   Product_Category  21663 non-null  object
 8   Revenue           21663 non-null  float64
 9   Bounce_Flag       21663 non-null  object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 1.7+ MB

In [18]:
#imp information about dataset's numeric columns

df.describe()

                           Timestamp       Revenue
count                          21663  21663.000000
mean   2025-10-16 19:56:22.920740608     54.304841
min              2025-10-01 19:30:17      0.000000
25%              2025-10-09 08:31:38      0.000000
50%              2025-10-16 19:47:21      0.000000
75%              2025-10-24 08:13:17      0.000000
max              2025-10-31 19:25:15   1998.510000
std                              NaN    262.692471

In [19]:
#important information about all columns

df.describe(include = "object")

,User_ID,Session_ID,Event,Device,Region,Channel,Product_Category,Bounce_Flag
count,21663,21663,21663,21663,21663,21663,21663,21663
unique,10000,10000,4,3,4,4,5,2
top,USR09979,SES09979,Browse,Tablet,West,Google Ads,Electronics,Yes
freq,4,4,10000,7237,5462,5435,4405,17343

In [20]:
#shape of dataset

df.shape

(21663, 10)

In [21]:
pd.set_option("display.max_rows", None)

In [22]:
pd.set_option("display.max_rows", None)

In [ ]:
df

#Data Preprocessing and Cleaning